#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "7721687137:AAG0eLiP6k0IuFD7ROcSHyITh2pY3py_-TI")
    API_ID = int os.environ["API_ID", "18156248"]
    API_HASH = os.environ["API_HASH", "db946fb6805b1a698c679626b617e77a"]
    AUTH_USERS = ("2052075731")
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
